plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "lib/generators/**/*.rb"

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/generators/**/*"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
